QUESTIONS = [
    # coca-cola
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "factual",
     "question": "What was Coca-Cola's total net revenues for fiscal year 2022?",
     "ground_truth": "$43.0 billion"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "factual",
     "question": "What was Coca-Cola's net income attributable to shareowners in 2022?",
     "ground_truth": "$9.5 billion"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "factual",
     "question": "What was Coca-Cola's organic revenue growth rate in 2022?",
     "ground_truth": "16%"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "factual",
     "question": "How many countries does Coca-Cola operate in as of 2022?",
     "ground_truth": "More than 200 countries and territories"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "factual",
     "question": "What was Coca-Cola's operating income for fiscal year 2022?",
     "ground_truth": "$10.9 billion"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "factual",
     "question": "What was Coca-Cola's cash dividends paid per share in 2022?",
     "ground_truth": "$1.76 per share"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "factual",
     "question": "What was Coca-Cola's total assets at end of fiscal year 2022?",
     "ground_truth": "$92.8 billion"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "factual",
     "question": "What was Coca-Cola's free cash flow in fiscal year 2022?",
     "ground_truth": "Approximately $9.5 billion"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Coca-Cola's earnings per diluted share in fiscal year 2022?",
     "ground_truth": "$2.19"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Coca-Cola's comparable (non-GAAP) EPS in fiscal year 2022?",
     "ground_truth": "$2.48"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Coca-Cola's gross profit margin in fiscal year 2022?",
     "ground_truth": "Approximately 58%"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "numerical",
     "question": "By what percentage did Coca-Cola's net revenues grow in 2022 versus 2021?",
     "ground_truth": "Approximately 11%"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "reasoning",
     "question": "How does Coca-Cola describe its pricing strategy in response to inflation in 2022?",
     "ground_truth": "Revenue growth management including price increases and package mix shifts to offset input cost inflation"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "reasoning",
     "question": "What risks does Coca-Cola identify related to its bottling partners and franchise model?",
     "ground_truth": "Bottler financial health, ability to invest in infrastructure, compliance with brand standards, concentration risk"},
    {"doc": "COCACOLA_2022_10K.pdf", "question_type": "reasoning",
     "question": "What does Coca-Cola's management say about currency headwinds and their impact on reported results in 2022?",
     "ground_truth": "Strong dollar created significant currency headwinds reducing reported revenue growth, organic growth outpaced reported growth substantially"},

    # amazon
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "factual",
     "question": "What was Amazon's total net sales for fiscal year 2022?",
     "ground_truth": "$514.0 billion"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "factual",
     "question": "What was Amazon Web Services net sales in 2022?",
     "ground_truth": "$80.1 billion"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "factual",
     "question": "What was AWS operating income in fiscal year 2022?",
     "ground_truth": "$22.8 billion"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "factual",
     "question": "What was Amazon's North America segment net sales in 2022?",
     "ground_truth": "$315.9 billion"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "factual",
     "question": "What was Amazon's advertising services revenue in 2022?",
     "ground_truth": "$38.0 billion"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "factual",
     "question": "How many full and part-time employees did Amazon have at end of 2022?",
     "ground_truth": "Approximately 1.54 million"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "factual",
     "question": "What was Amazon's subscription services revenue in 2022?",
     "ground_truth": "$35.2 billion"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "factual",
     "question": "What was Amazon's International segment net sales in 2022?",
     "ground_truth": "$118.0 billion"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Amazon's net loss for fiscal year 2022?",
     "ground_truth": "$2.7 billion net loss"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Amazon's capital expenditure in fiscal year 2022?",
     "ground_truth": "Approximately $63.6 billion"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Amazon's free cash flow in fiscal year 2022?",
     "ground_truth": "Negative, approximately -$19.7 billion"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "reasoning",
     "question": "What were the main reasons for Amazon's decline in profitability in 2022?",
     "ground_truth": "Overcapacity in fulfillment network, higher labor costs, increased energy costs, Rivian investment loss"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "reasoning",
     "question": "What key risks does Amazon identify related to its cloud computing business?",
     "ground_truth": "Competition, security breaches, outages, pricing pressure, regulatory requirements, data center capacity"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "reasoning",
     "question": "How does Amazon describe its approach to long-term investment versus short-term profitability?",
     "ground_truth": "Amazon prioritizes long-term customer value and market leadership over short-term profits"},
    {"doc": "AMAZON_2022_10K.pdf", "question_type": "reasoning",
     "question": "What is Amazon's strategy for growing its advertising business?",
     "ground_truth": "Leveraging customer purchase data, sponsored products, streaming ads, third-party seller advertising"},

    # american express
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "factual",
     "question": "What was American Express total revenues net of interest expense in 2022?",
     "ground_truth": "$52.9 billion"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "factual",
     "question": "What was American Express net income in fiscal year 2022?",
     "ground_truth": "$7.5 billion"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "factual",
     "question": "What was American Express billed business volume in 2022?",
     "ground_truth": "$1.5 trillion"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "factual",
     "question": "How many cards in force did American Express have at end of 2022?",
     "ground_truth": "Approximately 133.3 million"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "factual",
     "question": "What was American Express provision for credit losses in 2022?",
     "ground_truth": "$2.3 billion"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "factual",
     "question": "What was American Express discount revenue in 2022?",
     "ground_truth": "$36.3 billion"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "factual",
     "question": "What was American Express net interest income in 2022?",
     "ground_truth": "$11.2 billion"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "factual",
     "question": "How many new cards did American Express acquire in 2022?",
     "ground_truth": "Approximately 12.5 million new cards"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "factual",
     "question": "What was American Express total assets at end of 2022?",
     "ground_truth": "$228.5 billion"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "numerical",
     "question": "What was American Express earnings per diluted share in 2022?",
     "ground_truth": "$9.85"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "numerical",
     "question": "What was American Express return on average equity in 2022?",
     "ground_truth": "Approximately 31%"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "numerical",
     "question": "What was the American Express net write-off rate in 2022?",
     "ground_truth": "1.5%"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "reasoning",
     "question": "What were the primary drivers of American Express revenue growth in 2022?",
     "ground_truth": "Record card member spending, travel and entertainment recovery, new card acquisitions, net interest income growth"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "reasoning",
     "question": "How does American Express describe its competitive positioning against Visa and Mastercard?",
     "ground_truth": "Closed-loop network, premium spend demographics, merchant relationships, integrated issuer-acquirer model"},
    {"doc": "AMERICANEXPRESS_2022_10K.pdf", "question_type": "reasoning",
     "question": "What risks does American Express identify related to economic downturns?",
     "ground_truth": "Credit losses increase, spend volumes decline, delinquency rates rise, provision requirements increase"},

    # apple
    {"doc": "APPLE_2022_10K.pdf", "question_type": "factual",
     "question": "What was Apple's total net sales for fiscal year 2022?",
     "ground_truth": "$394.3 billion"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "factual",
     "question": "What were Apple's iPhone net sales in fiscal year 2022?",
     "ground_truth": "$205.5 billion"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "factual",
     "question": "What were Apple's Services net sales in fiscal year 2022?",
     "ground_truth": "$78.1 billion"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "factual",
     "question": "What were Apple's Mac net sales in fiscal year 2022?",
     "ground_truth": "$40.2 billion"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "factual",
     "question": "What was Apple's iPad net sales in fiscal year 2022?",
     "ground_truth": "$29.3 billion"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "factual",
     "question": "What was Apple's total cash and cash equivalents at end of fiscal year 2022?",
     "ground_truth": "$23.6 billion"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "factual",
     "question": "What was Apple's research and development expense in fiscal year 2022?",
     "ground_truth": "$26.3 billion"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "factual",
     "question": "How many shares of Apple common stock were repurchased in fiscal year 2022?",
     "ground_truth": "Approximately 568 million shares"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Apple's gross margin percentage in fiscal year 2022?",
     "ground_truth": "43.3%"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Apple's net income for fiscal year 2022?",
     "ground_truth": "$99.8 billion"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Apple's earnings per diluted share in fiscal year 2022?",
     "ground_truth": "$6.11"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "numerical",
     "question": "What percentage of Apple's net sales came from international markets in 2022?",
     "ground_truth": "Approximately 58%"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "reasoning",
     "question": "Why did Apple's Services segment grow faster than hardware in fiscal year 2022?",
     "ground_truth": "Services growth driven by advertising, App Store, Apple Music, iCloud subscriptions and licensing"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "reasoning",
     "question": "What are the primary risk factors Apple identifies related to its supply chain?",
     "ground_truth": "Single or limited source suppliers, concentration in Asia Pacific manufacturing, geopolitical risks"},
    {"doc": "APPLE_2022_10K.pdf", "question_type": "reasoning",
     "question": "What competitive advantages does Apple describe in its annual report?",
     "ground_truth": "Ecosystem integration, hardware-software design, brand loyalty, retail presence, developer platform"},

    # best buy
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "factual",
     "question": "What was Best Buy total revenue for fiscal year 2022?",
     "ground_truth": "$51.8 billion"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "factual",
     "question": "What was Best Buy net earnings in fiscal year 2022?",
     "ground_truth": "$2.0 billion"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "factual",
     "question": "How many Best Buy stores were open at end of fiscal year 2022?",
     "ground_truth": "Approximately 1,144 stores in the US"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "factual",
     "question": "What was Best Buy online revenue as a percentage of domestic revenue?",
     "ground_truth": "Approximately 33%"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "factual",
     "question": "What was Best Buy's share repurchase amount in fiscal year 2022?",
     "ground_truth": "Approximately $3.5 billion"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "factual",
     "question": "What was Best Buy international revenue in fiscal year 2022?",
     "ground_truth": "Approximately $3.9 billion"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "factual",
     "question": "What was Best Buy's dividend per share in fiscal year 2022?",
     "ground_truth": "$2.80 per share"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "factual",
     "question": "What were Best Buy's selling general and administrative expenses in fiscal 2022?",
     "ground_truth": "$9.7 billion"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Best Buy comparable sales growth in fiscal year 2022?",
     "ground_truth": "10.4%"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Best Buy gross profit rate in fiscal year 2022?",
     "ground_truth": "23.5%"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Best Buy earnings per diluted share in fiscal year 2022?",
     "ground_truth": "$8.27"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Best Buy operating income in fiscal year 2022?",
     "ground_truth": "$2.3 billion"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "reasoning",
     "question": "What are Best Buy's primary competitive threats identified in the annual report?",
     "ground_truth": "Amazon and online retailers, Walmart, Costco, price competition, manufacturer direct sales"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "reasoning",
     "question": "How does Best Buy describe its Totaltech membership program?",
     "ground_truth": "Annual membership providing tech support, extended warranties, discounts, free delivery and installation"},
    {"doc": "BESTBUY_2022_10K.pdf", "question_type": "reasoning",
     "question": "What supply chain risks does Best Buy identify in its 10-K?",
     "ground_truth": "Vendor concentration, shipping disruptions, port congestion, component shortages, international sourcing risk"},

    # ebay
    {"doc": "EBAY_2022_10K.pdf", "question_type": "factual",
     "question": "What was eBay's total net revenues for fiscal year 2022?",
     "ground_truth": "$9.8 billion"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "factual",
     "question": "How many active buyers did eBay have at end of 2022?",
     "ground_truth": "Approximately 134 million active buyers"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "factual",
     "question": "What was eBay's advertising revenue in fiscal year 2022?",
     "ground_truth": "Approximately $1.2 billion"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "factual",
     "question": "What was eBay's operating income in fiscal year 2022?",
     "ground_truth": "Approximately $1.9 billion"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "factual",
     "question": "How much did eBay return to shareholders through buybacks in 2022?",
     "ground_truth": "Approximately $3.0 billion"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "factual",
     "question": "What was eBay's cash and cash equivalents at end of 2022?",
     "ground_truth": "Approximately $2.1 billion"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "factual",
     "question": "What was eBay's international net revenues in fiscal year 2022?",
     "ground_truth": "Approximately $5.4 billion"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "factual",
     "question": "What was eBay's total net revenues for fiscal year 2021 for comparison?",
     "ground_truth": "Approximately $10.4 billion"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "numerical",
     "question": "What was eBay's gross merchandise volume in 2022?",
     "ground_truth": "$73.9 billion"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "numerical",
     "question": "What was eBay's net income for fiscal year 2022?",
     "ground_truth": "$1.3 billion"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "numerical",
     "question": "What was eBay's take rate or revenue as a percentage of GMV in 2022?",
     "ground_truth": "Approximately 13.3%"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "numerical",
     "question": "What was eBay's earnings per diluted share in fiscal year 2022?",
     "ground_truth": "Approximately $2.07"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "reasoning",
     "question": "What is eBay's focus market strategy as described in the 2022 annual report?",
     "ground_truth": "Focus on enthusiast buyers in categories like trading cards, sneakers, luxury handbags, auto parts"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "reasoning",
     "question": "What are the main competitive risks eBay faces according to its 10-K?",
     "ground_truth": "Amazon, Etsy, social commerce platforms, international competitors, declining active buyers"},
    {"doc": "EBAY_2022_10K.pdf", "question_type": "reasoning",
     "question": "What strategic investments is eBay making to grow its business according to the 10-K?",
     "ground_truth": "Focus categories, advertising growth, authentication services, payments expansion, international markets"},

    # jpmorgan
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "factual",
     "question": "What was JPMorgan Chase's total net revenue for fiscal year 2022?",
     "ground_truth": "$128.7 billion"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "factual",
     "question": "What was JPMorgan Chase's net income for fiscal year 2022?",
     "ground_truth": "$37.7 billion"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "factual",
     "question": "What were JPMorgan Chase's total assets at end of fiscal year 2022?",
     "ground_truth": "$3.67 trillion"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "factual",
     "question": "What was JPMorgan's Consumer and Community Banking net revenue in 2022?",
     "ground_truth": "$57.4 billion"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "factual",
     "question": "What was JPMorgan's provision for credit losses in fiscal year 2022?",
     "ground_truth": "$6.4 billion"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "factual",
     "question": "What was JPMorgan's Corporate and Investment Bank net revenue in 2022?",
     "ground_truth": "$47.0 billion"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "factual",
     "question": "How many employees did JPMorgan Chase have at end of 2022?",
     "ground_truth": "Approximately 293,723 employees"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "factual",
     "question": "What was JPMorgan's net interest income in fiscal year 2022?",
     "ground_truth": "$66.3 billion"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "numerical",
     "question": "What was JPMorgan Chase's return on equity in fiscal year 2022?",
     "ground_truth": "12%"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "numerical",
     "question": "What was JPMorgan Chase's CET1 capital ratio at end of 2022?",
     "ground_truth": "15.0%"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "numerical",
     "question": "What was JPMorgan's earnings per diluted share in fiscal year 2022?",
     "ground_truth": "$12.09"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "numerical",
     "question": "What was JPMorgan's overhead ratio in fiscal year 2022?",
     "ground_truth": "57%"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "reasoning",
     "question": "How did rising interest rates affect JPMorgan's net interest income in 2022?",
     "ground_truth": "Rising rates significantly increased net interest income due to rate-sensitive assets repricing upward"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "reasoning",
     "question": "What major risks does JPMorgan identify related to the macroeconomic environment in 2022?",
     "ground_truth": "Recession risk, inflation, geopolitical instability from Russia-Ukraine war, credit quality deterioration"},
    {"doc": "JPMORGAN_2022_10K.pdf", "question_type": "reasoning",
     "question": "What does JPMorgan's management discussion say about investment banking revenue trends in 2022?",
     "ground_truth": "Investment banking fees declined significantly due to market volatility reducing IPO and M&A activity"},

    # netflix
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "factual",
     "question": "What was Netflix total revenues for fiscal year 2022?",
     "ground_truth": "$31.6 billion"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "factual",
     "question": "How many global streaming paid memberships did Netflix have at end of 2022?",
     "ground_truth": "231.7 million paid memberships"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "factual",
     "question": "What was Netflix net income for fiscal year 2022?",
     "ground_truth": "$4.5 billion"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "factual",
     "question": "What was Netflix average monthly revenue per membership in 2022?",
     "ground_truth": "Approximately $11.67"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "factual",
     "question": "What was Netflix content spend or amortization in fiscal year 2022?",
     "ground_truth": "Approximately $14.0 billion in content amortization"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "factual",
     "question": "What was Netflix United States and Canada streaming revenues in 2022?",
     "ground_truth": "$14.9 billion"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "factual",
     "question": "How much long-term debt did Netflix have at end of fiscal year 2022?",
     "ground_truth": "Approximately $14.4 billion"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "factual",
     "question": "What was Netflix earnings per diluted share in fiscal year 2022?",
     "ground_truth": "$9.95"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "factual",
     "question": "What was Netflix Latin America streaming revenues in 2022?",
     "ground_truth": "$4.0 billion"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Netflix operating income for fiscal year 2022?",
     "ground_truth": "$5.6 billion"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Netflix operating margin in fiscal year 2022?",
     "ground_truth": "17.8%"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Netflix free cash flow in fiscal year 2022?",
     "ground_truth": "Approximately $1.6 billion positive free cash flow"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "reasoning",
     "question": "What were the main reasons Netflix lost subscribers in early 2022?",
     "ground_truth": "Password sharing, competition, price increases, content slate timing, Russia suspension of service"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "reasoning",
     "question": "How does Netflix describe its new advertising-supported tier strategy?",
     "ground_truth": "Lower price ad-supported plan launched to grow membership, attract price-sensitive consumers, add advertising revenue stream"},
    {"doc": "NETFLIX_2022_10K.pdf", "question_type": "reasoning",
     "question": "What competitive risks does Netflix identify in its 2022 annual report?",
     "ground_truth": "Disney+, HBO Max, Amazon Prime Video, YouTube, gaming, linear TV, password sharing from non-paying users"},

    # oracle
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "factual",
     "question": "What was Oracle total revenues for fiscal year 2022?",
     "ground_truth": "$42.4 billion"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "factual",
     "question": "What was Oracle cloud services and license support revenues in fiscal year 2022?",
     "ground_truth": "$33.1 billion"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "factual",
     "question": "What was Oracle net income for fiscal year 2022?",
     "ground_truth": "$6.7 billion"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "factual",
     "question": "What was Oracle Infrastructure as a Service revenue in fiscal year 2022?",
     "ground_truth": "Approximately $1.8 billion"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "factual",
     "question": "What was Oracle's hardware revenues in fiscal year 2022?",
     "ground_truth": "Approximately $3.3 billion"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "factual",
     "question": "What was Oracle's total deferred revenue at end of fiscal year 2022?",
     "ground_truth": "Approximately $12.3 billion"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "factual",
     "question": "What was Oracle Americas revenues in fiscal year 2022?",
     "ground_truth": "Approximately $22.8 billion"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "factual",
     "question": "What was Oracle's earnings per diluted share in fiscal year 2022?",
     "ground_truth": "$3.05"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Oracle's total cloud revenue growth rate in fiscal year 2022?",
     "ground_truth": "Approximately 22%"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Oracle operating margin in fiscal year 2022?",
     "ground_truth": "Approximately 27%"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Oracle's research and development expense as percentage of revenue in 2022?",
     "ground_truth": "Approximately 15%"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Oracle's operating cash flow in fiscal year 2022?",
     "ground_truth": "Approximately $13.0 billion"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "reasoning",
     "question": "How does Oracle describe its competitive strategy against AWS Azure and Google Cloud?",
     "ground_truth": "Price performance advantage, autonomous database, enterprise workload migration, existing customer base"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "reasoning",
     "question": "What risks does Oracle identify related to its Cerner acquisition?",
     "ground_truth": "Integration challenges, customer retention, increased debt load, healthcare industry complexities"},
    {"doc": "ORACLE_2022_10K.pdf", "question_type": "reasoning",
     "question": "What does Oracle's management discussion say about the shift from on-premises to cloud?",
     "ground_truth": "Cloud transition accelerating, license revenues declining as customers migrate to subscription cloud services"},

    # walmart
    {"doc": "WALMART_2022_10K.pdf", "question_type": "factual",
     "question": "What was Walmart total revenues for fiscal year 2022?",
     "ground_truth": "$572.8 billion"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "factual",
     "question": "What was Walmart US net sales in fiscal year 2022?",
     "ground_truth": "$393.5 billion"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "factual",
     "question": "What was Walmart's consolidated net income for fiscal year 2022?",
     "ground_truth": "$13.7 billion"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "factual",
     "question": "What was Walmart International net sales in fiscal year 2022?",
     "ground_truth": "$101.0 billion"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "factual",
     "question": "How many Walmart US stores were open at end of fiscal year 2022?",
     "ground_truth": "Approximately 4,742 stores"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "factual",
     "question": "What was Walmart's Sam's Club net sales in fiscal year 2022?",
     "ground_truth": "$73.6 billion"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "factual",
     "question": "What was Walmart's capital expenditure in fiscal year 2022?",
     "ground_truth": "Approximately $13.1 billion"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "factual",
     "question": "How many total associates did Walmart employ globally at end of fiscal year 2022?",
     "ground_truth": "Approximately 2.3 million associates worldwide"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Walmart US comparable sales increase in fiscal year 2022?",
     "ground_truth": "6.4%"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Walmart's operating income in fiscal year 2022?",
     "ground_truth": "$24.9 billion"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Walmart's earnings per diluted share in fiscal year 2022?",
     "ground_truth": "$4.87"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "numerical",
     "question": "What was Walmart's gross profit rate in fiscal year 2022?",
     "ground_truth": "24.3%"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "reasoning",
     "question": "How is Walmart investing in its ecommerce capabilities according to the 2022 annual report?",
     "ground_truth": "Marketplace growth, fulfillment services, Walmart+ subscription, advertising business, supply chain automation"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "reasoning",
     "question": "What supply chain and inflation risks does Walmart identify in fiscal year 2022?",
     "ground_truth": "Cost pressures from inflation, supply chain disruptions, freight costs, inventory management challenges"},
    {"doc": "WALMART_2022_10K.pdf", "question_type": "reasoning",
     "question": "What is Walmart's strategy for competing with Amazon according to the 2022 10-K?",
     "ground_truth": "Omnichannel model combining physical stores with ecommerce, Walmart+ membership, grocery delivery advantage"},
]
